#
# Zentrale Konfigurationsdatei wird von cloud-init und allen Helper-Scripts verwendet 
#
# Definiert u.a. welche Scripts und wie die einzelnen VMs aufgebaut sind (Memory, Storage, CPU Cores)
# 
# ACHTUNG: Array Eintrage (scripts, repositories) muessen als a,b,c ohne Space eingetragen werden, sonst gibt es Probleme mit Umgebungsvariablen

######### Informatik Module siehe https://cf.ict-berufsbildung.ch/modules.php?name=Mbk&a=20100&noheader=1&clang=de #########

# Allgemeine Kubernetes Umgebung - nicht Modul gebunden. Mit TBZ Deployer
m000master:
  vm:  
    storage: 32
    memory:  3584
    cores: 2
    count: 1
  services:
    nfs: true
    docker: true
    k8s: master
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: tbz-deployer.sh
  repositories: 
  
m000worker:
  vm:  
    storage: 32
    memory:  3584
    cores: 2
    count: 5
  services:
    nfs: true
    docker: true
    k8s: worker
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: 
  repositories:   

# Modul 122: Automatisieren mit Skripten  
m122:
  vm:  
    storage: 8
    memory:  2048
    cores: 2
    count: 2
  services:
    nfs: true
    docker: false
    k8s: 
    wireguard: use
    ssh: generate
    samba: true
    firewall: false
  scripts: 
  repositories: https://github.com/tbz-it/M122

# Modul 141: Datenbanksystem in Betrieb nehmen
m141:
  vm:  
    storage: 32
    memory:  3584
    cores: 2
    count: 6
  services:
    nfs: true
    docker: true
    k8s: master
    wireguard: use
    ssh: use
    samba: true
    firewall: false
  scripts: m141.sh
  repositories: 
  
# Modul 239: Internet Server in Betrieb nehmen  
m239:
  vm:  
    storage: 8
    memory:  2048
    cores: 2
    count: 24
  services:
    nfs: true
    docker: false
    k8s: 
    wireguard: use
    ssh: use
    samba: true
    firewall: true
  scripts: apache.sh
  repositories: 
   
# Modul 242: Mikroprozessoranwendung realisieren
m242:
  vm:  
    storage: 32
    memory:  7680
    cores: 4
    count: 6
  services:
    nfs: true
    docker: true
    k8s: master
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: modtec.sh
  repositories: https://github.com/mc-b/duk,https://github.com/mc-b/mlg 
  
# Modul 300: Plattformuebergreifende Dienste in ein Netzwerk integrieren
m300:
  vm:  
    storage: 32
    memory:  6144
    cores: 2
    count: 6
  services:
    nfs: true
    docker: true
    k8s: master
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: 
  repositories: https://github.com/mc-b/misegr,https://github.com/mc-b/duk
  
######### Digicomp Kurse siehe https://github.com/mc-b ######### 

# Docker und Kubernetes – Uebersicht und Einsatz - https://github.com/mc-b/duk
dukmaster:
  vm:  
    storage: 32
    memory:  7680
    cores: 2
    count: 1
  services:
    nfs: true
    docker: true
    k8s: master
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: 
  repositories: https://github.com/mc-b/misegr,https://github.com/mc-b/duk  
dukworker:  
  vm:  
    storage: 32
    memory:  7680
    cores: 2
    count: 5
  services:
    nfs: true
    docker: true
    k8s: worker
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: 
  repositories:  
  
# Internet der Dinge im Einsatz - https://github.com/mc-b/iotkitv3
iotein:
  vm:  
    storage: 32
    memory:  7680
    cores: 2
    count: 6
  services:
    nfs: true
    docker: true
    k8s: master
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: 
  repositories: https://github.com/mc-b/misegr,https://github.com/mc-b/duk,https://github.com/mc-b/mlg,https://github.com/mc-b/iot.kafka

# DevOps Engineering Practices & Tools (CDI) - https://github.com/mc-b/cdi
cdi:
  vm:  
    storage: 32
    memory:  7680
    cores: 2
    count: 6
  services:
    nfs: true
    docker: true
    k8s: master
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: 
  repositories: https://github.com/mc-b/misegr,https://github.com/mc-b/duk,https://github.com/mc-b/cdi 
  
# Microservices-Grundlagen - https://github.com/mc-b/misegr 
misegr:
  vm:  
    storage: 32
    memory:  7680
    cores: 2
    count: 6
  services:
    nfs: true
    docker: true
    k8s: master
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: 
  repositories: https://github.com/mc-b/misegr,https://github.com/mc-b/duk   
   
# Machine Learning Grundlagen - https://github.com/mc-b/mlg
mlg:
  vm:  
    storage: 32
    memory:  7680
    cores: 2
    count: 6
  services:
    nfs: true
    docker: true
    k8s: master
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: 
  repositories: https://github.com/mc-b/misegr,https://github.com/mc-b/duk,https://github.com/mc-b/mlg 
    
# IoT, Microservices, Machine Learning und DevOps – Moderne architektur-relevante Methoden und Technologien - https://github.com/mc-b/modtec
modtec:
  vm:  
    storage: 32
    memory:  7680
    cores: 4
    count: 6
  services:
    nfs: true
    docker: true
    k8s: master
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: modtec.sh
  repositories: https://github.com/mc-b/duk,https://github.com/mc-b/mlg  
  
# Spezialumgebungen fuer Demos uns Referate
dukdemo:
  vm:  
    storage: 32
    memory:  16384
    cores: 4
    count: 1
  services:
    nfs: true
    docker: true
    k8s: master
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: modtec.sh
  repositories: https://github.com/mc-b/misegr,https://github.com/mc-b/duk,https://github.com/mc-b/mlg,https://github.com/mc-b/cdi,https://github.com/mc-b/duk-demo  

######### Docker und Kubernetes Varianten - zu Test und Demozwecken #########

# einfache Docker Umgebung
docker:
  vm:  
    storage: 8
    memory:  3584
    cores: 2
    count: 1
  services:
    nfs: true
    docker: true
    k8s: 
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: 
  repositories: 

# Lightweight Kubernetes - https://k3s.io/
k3s:
  vm:  
    storage: 8
    memory:  2048
    cores: 2
    count: 1
  services:
    nfs: true
    docker: false
    k8s: 
    wireguard: use
    ssh: use
    samba: false
    firewall: false
  scripts: k3s.sh
  repositories:  